// @generated by tools/slicer. Do not edit.

/// A short recorded keystroke, embedded in the binary.
pub struct Slice {
    pub path: &'static str,
    pub wav: &'static [u8],
}

pub static SLICES: &[Slice] = &[
    Slice { path: "leopold-fc660m/01.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/01.wav") },
    Slice { path: "leopold-fc660m/02.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/02.wav") },
    Slice { path: "leopold-fc660m/03.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/03.wav") },
    Slice { path: "leopold-fc660m/04.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/04.wav") },
    Slice { path: "leopold-fc660m/05.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/05.wav") },
    Slice { path: "leopold-fc660m/06.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/06.wav") },
    Slice { path: "leopold-fc660m/07.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/07.wav") },
    Slice { path: "leopold-fc660m/08.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/08.wav") },
    Slice { path: "leopold-fc660m/09.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/09.wav") },
    Slice { path: "leopold-fc660m/10.wav", wav: include_bytes!("../assets/slices/leopold-fc660m/10.wav") },
    Slice { path: "hhkb-topre/01.wav", wav: include_bytes!("../assets/slices/hhkb-topre/01.wav") },
    Slice { path: "hhkb-topre/02.wav", wav: include_bytes!("../assets/slices/hhkb-topre/02.wav") },
    Slice { path: "hhkb-topre/03.wav", wav: include_bytes!("../assets/slices/hhkb-topre/03.wav") },
    Slice { path: "hhkb-topre/04.wav", wav: include_bytes!("../assets/slices/hhkb-topre/04.wav") },
    Slice { path: "hhkb-topre/05.wav", wav: include_bytes!("../assets/slices/hhkb-topre/05.wav") },
    Slice { path: "hhkb-topre/06.wav", wav: include_bytes!("../assets/slices/hhkb-topre/06.wav") },
    Slice { path: "hhkb-topre/07.wav", wav: include_bytes!("../assets/slices/hhkb-topre/07.wav") },
    Slice { path: "hhkb-topre/08.wav", wav: include_bytes!("../assets/slices/hhkb-topre/08.wav") },
    Slice { path: "hhkb-topre/09.wav", wav: include_bytes!("../assets/slices/hhkb-topre/09.wav") },
    Slice { path: "hhkb-topre/10.wav", wav: include_bytes!("../assets/slices/hhkb-topre/10.wav") },
    Slice { path: "whitefox-hako-violet/01.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/01.wav") },
    Slice { path: "whitefox-hako-violet/02.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/02.wav") },
    Slice { path: "whitefox-hako-violet/03.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/03.wav") },
    Slice { path: "whitefox-hako-violet/04.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/04.wav") },
    Slice { path: "whitefox-hako-violet/05.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/05.wav") },
    Slice { path: "whitefox-hako-violet/06.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/06.wav") },
    Slice { path: "whitefox-hako-violet/07.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/07.wav") },
    Slice { path: "whitefox-hako-violet/08.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/08.wav") },
    Slice { path: "whitefox-hako-violet/09.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/09.wav") },
    Slice { path: "whitefox-hako-violet/10.wav", wav: include_bytes!("../assets/slices/whitefox-hako-violet/10.wav") },
];

/// (directory slug, display name), straight from the manifest.
pub static BOARDS: &[(&str, &str)] = &[
    ("leopold-fc660m", "Leopold FC660M"),
    ("hhkb-topre", "HHKB Topre"),
    ("whitefox-hako-violet", "WhiteFox Hako Violet"),
];

